GetElapsedTime no longer vomits an error
System.ArgumentOutOfRangeException: 'The added or subtracted value results in an un-representable DateTime.' is fixed